### ISSUE TITLE
TypeError: (0 , _styledComponents.css) is not a function

### ISSUE THREAD

**Issue by slipperypenguin** [grommet/grommet-icons#46]
Hello, I'm using `grommet-icons` in a file that is causing my Jest tests to fail. The tests pass when the component that is using `grommet-icons` is removed and the error I'm receiving from Jest traces back to a file inside the `grommet-icons` node_module. Everything seems to work fine outside of the tests.

## Version
grommet-icons: 0.14.0,
styled-components: 2.2.4,
babel-plugin-styled-components: 1.3.0
babel-jest: 21.2.0,
enzyme: 3.2.0,
jest: 21.2.1,

## Reproduction
I've tried to include/condense the relevant files that seem to be causing the issue. If other files are needed that I haven't included here, just let me know and I'll get that over!

Example-test.js
```js
/**
 * @jest-environment jsdom
 */
/* eslint-disable function-paren-newline */

import React from 'react';
import NoteCard from '../../../src/components/NoteCard/NoteCard';
import NotesSideBar from '../../../src/layouts/NotesSideBar';
import SideBar from '../../../src/components/SideBar/SideBar';
import { shallow, mount, configure } from 'enzyme';
import Adapter from 'enzyme-adapter-react-16';
import 'jest-styled-components';

configure({ adapter: new Adapter() });

describe('Test that NotesSideBar and childComponents render', () => {
  test('NotesSideBar renders', () => {
    const component = shallow(
      <NotesSideBar
        notes={notes}
        showSidebar={true}
        selectNote={() => {}}
        appendNote={() => {}}
        deleteNote={() => {}}
        userInfo={testUserInfo}
      />);
    expect(component).toMatchSnapshot();
  });

  test('NoteCard renders', () => {
    const component = shallow(
      <NoteCard
        note={notes[0]}
        selectNote={() => {}}
      />);
    expect(component).toMatchSnapshot();
  });
});

```

The file that contains `grommet-icons` and `styled-components`:
NotesSideBar.jsx

```js
import React, { Component } from 'react';
import PropTypes from 'prop-types';
import SideBar from '../components/SideBar/SideBar';
import Box from '../components/Box/Box';
import { css, ThemeProvider } from 'styled-components';
import { Image, Notes, TextWrap, Gallery } from 'grommet-icons';

class NotesSideBar extends Component {
  constructor(props) {
    super(props);
    this.state = {
      notes: this.props.notes,
      mine: false
    };
  }

  render() {
    const theme = {
      icon: {
        color: 'rgba(61,112,178,0.3)',
        extend: css`
          ${props => props.color === 'selected' && `
            fill: #3d70b2;
            stroke: #3d70b2;
          `}
          &:hover {
            cursor: pointer;
          }
        `,
      },
    };
    return (
      <SideBar colorIndex='neutral-1'
        notes={this.state.notes}
        noteTypes={<div>
          <hr style={{ margin: 0 }} />
          <Box pad='20px 0 0 0'>
            <h6>Show note types:</h6>
            <ThemeProvider theme={theme}>
              <Box justifyContent='space-between' width='130px' margin='0 10px'>
                <Notes color={this.state.text ? 'selected' : ''}
                  onClick={() => this.toggleState('text')} />
                <TextWrap color={this.state.textImage ? 'selected' : ''}
                  onClick={() => this.toggleState('textImage')} />
                <Image color={this.state.image ? 'selected' : ''}
                  onClick={() => this.toggleState('image')} />
                <Gallery color={this.state.multImg ? 'selected' : ''}
                  onClick={() => this.toggleState('multImg')} />
              </Box>
            </ThemeProvider>
          </Box>
        </div>}
        mine={this.state.mine}
          />
    );
  }
}

NotesSideBar.propTypes = {
  notes: PropTypes.array,
};

NotesSideBar.defaultProps = {
  notes: []
};

export default NotesSideBar;

```

## Steps to reproduce
The function in question that seems to be causing an issue ( from `node_modules/grommet-icons/StyledIcon.js` lines 15 - 26)
```js
var SIZE_MAP = {
  'large': (0, _styledComponents.css)(['width:', ';height:', ';'], function (props) {
    return props.theme.icon.size.large;
  }, function (props) {
    return props.theme.icon.size.large;
  }),
  'xlarge': (0, _styledComponents.css)(['width:', ';height:', ';'], function (props) {
    return props.theme.icon.size.xlarge;
  }, function (props) {
    return props.theme.icon.size.xlarge;
  })
};
```

## Expected Behavior
Expecting the Jest tests to pass, since they pass if `grommet-icons` is removed.

## Actual Behavior
The failing log from Jest:

```bash

 FAIL  __tests__/src/Notes/NotesSideBar.test.js
  ● Test suite failed to run

    TypeError: (0 , _styledComponents.css) is not a function
      
      at Object.<anonymous> (node_modules/grommet-icons/StyledIcon.js:16:38)
      at Object.<anonymous> (node_modules/grommet-icons/Icon.js:23:19)
      at Object.<anonymous> (node_modules/grommet-icons/icons/Accessibility.js:11:13)
      at Object.<anonymous> (node_modules/grommet-icons/icons/index.js:5:22)
      at Object.<anonymous> (node_modules/grommet-icons/index.js:6:14)
      at Object.<anonymous> (src/components/NoteCard/NoteCard.jsx:5:21)
      at Object.<anonymous> (__tests__/src/Notes/NotesSideBar.test.js:7:17)
          at Generator.next (<anonymous>)
          at new Promise (<anonymous>)
      at handle (node_modules/worker-farm/lib/child/index.js:44:8)
      at process.<anonymous> (node_modules/worker-farm/lib/child/index.js:51:3)
      at emitTwo (events.js:126:13)
      at process.emit (events.js:214:7)
      at emit (internal/child_process.js:772:12)
      at _combinedTickCallback (internal/process/next_tick.js:141:11)
      at process._tickCallback (internal/process/next_tick.js:180:9)


Test Suites: 1 failed, 2 passed, 3 total
Tests:       25 passed, 25 total
Snapshots:   0 total
Time:        3.411s
Ran all test suites.
npm ERR! Test failed.  See above for more details.
```

Screenshot of the same test result:
![screen shot 2017-12-06 at 2 05 28 pm](https://user-images.githubusercontent.com/3655354/33680186-cb119d7e-da8e-11e7-89f4-1a202908ace8.png)

**Comment by slipperypenguin** [comment]
Just figured out a solution [here](https://facebook.github.io/jest/docs/en/webpack.html#mocking-css-modules)

Looks like it was an issue with mocking css modules in Jest. 
In `package.json`:

### Old Setup
```json
"jest": {
    "setupFiles": [
      "raf/polyfill"
    ],
    "moduleNameMapper": {
      ".*css$": "<rootDir>/__mocks__/mockCSS.css",
      ".*svg$": "<rootDir>/__mocks__/mockSVG.svg",
      ".*png$": "<rootDir>/__mocks__/mockPNG.png"
    },
    "snapshotSerializers": [
      "enzyme-to-json/serializer"
    ]
  }
```

### New Setup
```json
"jest": {
    "setupFiles": [
      "raf/polyfill"
    ],
    "moduleNameMapper": {
      "\\.(jpg|jpeg|png|svg)$": "<rootDir>/__mocks__/fileMock.js",
      "\\.(css|less)$": "identity-obj-proxy"
    },
    "snapshotSerializers": [
      "enzyme-to-json/serializer"
    ]
  }
```
